version: '3'
services:
  nginx:
    image: nginx:1.12-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - /c/tayhh/docker/compose/test-app/nginx.conf:/etc/nginx/nginx.conf:ro
  web:
    build: .
    depends_on:
      - redis
    expose:
      - "5000"
  redis:
    image: redis:alpine